/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author nshut
 */
public class ManageBooks extends javax.swing.JFrame {
DefaultTableModel tableModel = new DefaultTableModel();
        private String db_url = "jdbc:postgresql://localhost:5432/GS_APACE_LMS";
        private String db_username = "postgres";
        private String db_passwd = "2804";
    /**
     * Creates new form ManageBooks
     */
        
    String bookName, classes;
    int bookId, quantity;
    DefaultTableModel model;
    
    public ManageBooks() {
        initComponents();
        SetBookToTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        bookIdTxt = new app.bolivia.swing.JCTextField();
        bookNameTxt = new app.bolivia.swing.JCTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        quantityTxt = new app.bolivia.swing.JCTextField();
        deleteBtn = new rojerusan.RSMaterialButtonCircle();
        addBtn = new rojerusan.RSMaterialButtonCircle();
        updateBtn = new rojerusan.RSMaterialButtonCircle();
        yearTxt = new app.bolivia.swing.JCTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        bookTable = new rojeru_san.complementos.RSTableMetro();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Rewind_48px.png"))); // NOI18N
        jLabel1.setText("Back");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 40));

        jLabel12.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Contact_26px.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Book Id:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        bookIdTxt.setBackground(new java.awt.Color(102, 102, 255));
        bookIdTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        bookIdTxt.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        bookIdTxt.setPhColor(new java.awt.Color(255, 255, 255));
        bookIdTxt.setPlaceholder("Enter Book Id...");
        jPanel1.add(bookIdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        bookNameTxt.setBackground(new java.awt.Color(102, 102, 255));
        bookNameTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        bookNameTxt.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        bookNameTxt.setPhColor(new java.awt.Color(255, 255, 255));
        bookNameTxt.setPlaceholder("Enter Book Name...");
        jPanel1.add(bookNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, -1));

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Moleskine_26px.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        jLabel17.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Book Name:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, -1, -1));

        jLabel18.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Unit_26px.png"))); // NOI18N
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 50, 40));

        jLabel19.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Quantity:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, -1, -1));

        quantityTxt.setBackground(new java.awt.Color(102, 102, 255));
        quantityTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        quantityTxt.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        quantityTxt.setPhColor(new java.awt.Color(255, 255, 255));
        quantityTxt.setPlaceholder("Enter Quantity...");
        jPanel1.add(quantityTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, -1, -1));

        deleteBtn.setText("DELETE");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        jPanel1.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 660, 110, 50));

        addBtn.setText("ADD");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        jPanel1.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 660, 110, 50));

        updateBtn.setText("UPDATE");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        jPanel1.add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 660, 110, 50));

        yearTxt.setBackground(new java.awt.Color(102, 102, 255));
        yearTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        yearTxt.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        yearTxt.setPhColor(new java.awt.Color(255, 255, 255));
        yearTxt.setPlaceholder("Enter Class...");
        jPanel1.add(yearTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 550, -1, -1));

        jLabel20.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Class/Year");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 520, -1, -1));

        jLabel15.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Moleskine_26px.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 830));

        jLabel23.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 0, 0));
        jLabel23.setText("X");
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(1490, 0, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 51, 51));
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Books_52px_1.png"))); // NOI18N
        jLabel25.setText("Manage Books");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 40, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 51, 51));
        jPanel3.setForeground(new java.awt.Color(0, 255, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 100, 400, 3));

        bookTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book Id", "Book Name", "Quantity", "Class(Year)"
            }
        ));
        bookTable.setColorBackgoundHead(new java.awt.Color(102, 102, 255));
        bookTable.setColorBordeFilas(new java.awt.Color(102, 102, 255));
        bookTable.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        bookTable.setColorSelBackgound(new java.awt.Color(204, 204, 204));
        bookTable.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 25)); // NOI18N
        bookTable.setFuenteFilas(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        bookTable.setFuenteFilasSelect(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        bookTable.setFuenteHead(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        bookTable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        bookTable.setRowHeight(35);
        bookTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(bookTable);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 1090, 690));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel22.setText("Copyright @TheMob 2023");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 810, -1, 20));

        setSize(new java.awt.Dimension(1523, 828));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

   public void SetBookToTable(){
       try{
           Connection con = DriverManager.getConnection(db_url, db_username, db_passwd);
           PreparedStatement pst = con.prepareCall("select * from books ");
           ResultSet result = pst.executeQuery();
           while(result.next()){
               int bookId = result.getInt("book_id");
               String bookName = result.getString("book_name");
               int quantity = result.getInt("quantity");
               String classes = result.getString("classes");
               
               Object[] obj = {bookId, bookName, quantity, classes};
               model =(DefaultTableModel ) bookTable.getModel();
               model.addRow(obj);
               
           }
       }catch(Exception ex){
           ex.printStackTrace();
       }
       
       
   } 
   
   public boolean addBook(){
       
       boolean isAdded = false;
       bookId = Integer.parseInt(bookIdTxt.getText());
       bookName = bookNameTxt.getText();
       quantity = Integer.parseInt(quantityTxt.getText());
       classes = yearTxt.getText();
       try{
           Connection con = DriverManager.getConnection(db_url, db_username, db_passwd);
           String sql = "insert into books values(?,?,?,?)";
           PreparedStatement pst = con.prepareStatement(sql);
           pst.setInt(1, bookId);
           pst.setString(2, bookName);
           pst.setInt(3, quantity);
           pst.setString(4, classes);
           
           int rowCount = pst.executeUpdate();
           if(rowCount >0){
               isAdded =true;
               
           }else{
               isAdded =false;
           }
           
       }catch(Exception ex){
           ex.printStackTrace();
       }
    return isAdded;
       
   }
   
   //Clear table
    public void clearTable(){
        DefaultTableModel model = (DefaultTableModel) bookTable.getModel();
        model.setRowCount(0);
        
    }
    
    public boolean updateBook(){
        boolean isUpdated = false;
       bookId = Integer.parseInt(bookIdTxt.getText());
       bookName = bookNameTxt.getText();
       quantity = Integer.parseInt(quantityTxt.getText());
       classes = yearTxt.getText();
       try{
           Connection con = DriverManager.getConnection(db_url, db_username, db_passwd);
           String sql = "update books set book_name = ?, quantity = ?, classes = ? where book_id = ?";
           PreparedStatement pst = con.prepareStatement(sql);
           pst.setString(1, bookName);
           pst.setInt(2, quantity);
           pst.setString(3, classes);
           pst.setInt(4, bookId);
           
           int rowCount = pst.executeUpdate();
           if(rowCount > 0){
               isUpdated = true;
           }else{
               isUpdated = false;
           }
       }catch(Exception ex){
           ex.printStackTrace();
       }
       
    return isUpdated;
    }
   
    public boolean deleteBook(){
        boolean isDeleted = false;
        bookId = Integer.parseInt(bookIdTxt.getText());
       bookName = bookNameTxt.getText();
       quantity = Integer.parseInt(quantityTxt.getText());
       classes = yearTxt.getText();
        
        try{
           Connection con = DriverManager.getConnection(db_url, db_username, db_passwd);
           String sql = "delete from books where book_id = ?";
           PreparedStatement pst = con.prepareStatement(sql);
           pst.setInt(1, bookId);
           pst.executeUpdate();
           
           int rowCount = pst.executeUpdate();
           if(rowCount> 0){
               isDeleted = true;
           }else{
               isDeleted = false;
           }
        }catch(Exception ex){
            ex.printStackTrace();
        }
        
    return isDeleted;
        
    }
    
    
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        HomePage page = new HomePage();
        page.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel23MouseClicked

    private void bookTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookTableMouseClicked
        int rowNumber = bookTable.getSelectedRow();
        TableModel model = bookTable.getModel();
        
        bookIdTxt.setText(model.getValueAt(rowNumber, 0).toString());
        bookNameTxt.setText(model.getValueAt(rowNumber, 1).toString());
        quantityTxt.setText(model.getValueAt(rowNumber, 2).toString());
        yearTxt.setText(model.getValueAt(rowNumber, 3).toString());
    }//GEN-LAST:event_bookTableMouseClicked

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        if(addBook()==true){
            JOptionPane.showMessageDialog(this, "Book Added Successfully.");
            clearTable();
            SetBookToTable();
        }else{
            JOptionPane.showMessageDialog(this, "There's Been a Duplication! Check Again.");
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        if(updateBook() ==true){
            JOptionPane.showMessageDialog(this, "Book Updated Successfully.");
            clearTable();
            SetBookToTable();
        }else{
            JOptionPane.showMessageDialog(this, "Book Failed To Update!");
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        if(!deleteBook()==true){
            JOptionPane.showMessageDialog(this, "Book Deleted Successfully.");
            clearTable();
            SetBookToTable();
        }else{
            JOptionPane.showMessageDialog(this, "Book Failed To Delete!");
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        HomePage page = new HomePage();
        page.setVisible(true);
        dispose();
    }//GEN-LAST:event_jPanel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageBooks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonCircle addBtn;
    private app.bolivia.swing.JCTextField bookIdTxt;
    private app.bolivia.swing.JCTextField bookNameTxt;
    private rojeru_san.complementos.RSTableMetro bookTable;
    private rojerusan.RSMaterialButtonCircle deleteBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private app.bolivia.swing.JCTextField quantityTxt;
    private rojerusan.RSMaterialButtonCircle updateBtn;
    private app.bolivia.swing.JCTextField yearTxt;
    // End of variables declaration//GEN-END:variables
}
