/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author nshut
 */
public class ManageTeachers extends javax.swing.JFrame {
DefaultTableModel tableModel = new DefaultTableModel();
        private String db_url = "jdbc:postgresql://localhost:5432/GS_APACE_LMS";
        private String db_username = "postgres";
        private String db_passwd = "2804";
    /**
     * Creates new form ManageBooks
     */
        
    String teacherName, bookName, classes;
    int teacherId, numberOfBooks;
    DefaultTableModel model;
    
    public ManageTeachers() {
        initComponents();
        SetTeacherToTable();
        setUpComboBox();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        teacherIdTxt = new app.bolivia.swing.JCTextField();
        teacherNameTxt = new app.bolivia.swing.JCTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        numberOfBookTxt = new app.bolivia.swing.JCTextField();
        deleteBtn = new rojerusan.RSMaterialButtonCircle();
        addBtn = new rojerusan.RSMaterialButtonCircle();
        updateBtn = new rojerusan.RSMaterialButtonCircle();
        jLabel20 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        yearTxt = new app.bolivia.swing.JCTextField();
        bookCombo = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        teacherTable = new rojeru_san.complementos.RSTableMetro();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(102, 102, 255));
        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Rewind_48px.png"))); // NOI18N
        jLabel1.setText("Back");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 40));

        jLabel12.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Contact_26px.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Enter Teacher's Id");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, -1));

        teacherIdTxt.setBackground(new java.awt.Color(0, 153, 0));
        teacherIdTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        teacherIdTxt.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        teacherIdTxt.setPhColor(new java.awt.Color(255, 255, 255));
        teacherIdTxt.setPlaceholder("Enter Teacher's Id...");
        jPanel1.add(teacherIdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 250, -1));

        teacherNameTxt.setBackground(new java.awt.Color(0, 153, 0));
        teacherNameTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        teacherNameTxt.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        teacherNameTxt.setPhColor(new java.awt.Color(255, 255, 255));
        teacherNameTxt.setPlaceholder("Enter Teacher's Name...");
        jPanel1.add(teacherNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 250, -1));

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Contact_26px.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jLabel17.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Teacher's Name");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));

        jLabel18.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Unit_26px.png"))); // NOI18N
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 50, 40));

        jLabel19.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Number of Books");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, -1, -1));

        numberOfBookTxt.setBackground(new java.awt.Color(0, 153, 0));
        numberOfBookTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        numberOfBookTxt.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        numberOfBookTxt.setPhColor(new java.awt.Color(255, 255, 255));
        numberOfBookTxt.setPlaceholder("Enter Number of Books...");
        jPanel1.add(numberOfBookTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 540, 250, -1));

        deleteBtn.setBackground(new java.awt.Color(125, 255, 51));
        deleteBtn.setText("DELETE");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        jPanel1.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 660, 110, 50));

        addBtn.setBackground(new java.awt.Color(102, 255, 51));
        addBtn.setText("ADD");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        jPanel1.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 660, 110, 50));

        updateBtn.setBackground(new java.awt.Color(125, 255, 51));
        updateBtn.setText("UPDATE");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        jPanel1.add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 660, 110, 50));

        jLabel20.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Book Name");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, -1, -1));

        jLabel15.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Moleskine_26px.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jLabel16.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Moleskine_26px.png"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, -1, -1));

        jLabel21.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Class/Year");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, -1, -1));

        yearTxt.setBackground(new java.awt.Color(0, 153, 0));
        yearTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        yearTxt.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        yearTxt.setPhColor(new java.awt.Color(255, 255, 255));
        yearTxt.setPlaceholder("Enter Class...");
        jPanel1.add(yearTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 250, -1));

        bookCombo.setBackground(new java.awt.Color(0, 153, 0));
        bookCombo.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        bookCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookComboActionPerformed(evt);
            }
        });
        jPanel1.add(bookCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 250, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 828));

        jLabel23.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 0, 0));
        jLabel23.setText("X");
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(1493, 0, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 153, 0));
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/teacher.png"))); // NOI18N
        jLabel25.setText("Manage Teachers");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 50, -1, -1));

        jPanel3.setBackground(new java.awt.Color(0, 153, 0));
        jPanel3.setForeground(new java.awt.Color(0, 255, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 130, 400, 3));

        teacherTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Teacher ID", "Name", "Book Name", "Class(Year)", "Number of Books"
            }
        ));
        teacherTable.setColorBackgoundHead(new java.awt.Color(0, 153, 0));
        teacherTable.setColorBordeFilas(new java.awt.Color(0, 153, 0));
        teacherTable.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        teacherTable.setColorSelBackgound(new java.awt.Color(204, 204, 204));
        teacherTable.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 25)); // NOI18N
        teacherTable.setFuenteFilas(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        teacherTable.setFuenteFilasSelect(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        teacherTable.setFuenteHead(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        teacherTable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        teacherTable.setRowHeight(35);
        teacherTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teacherTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(teacherTable);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 1110, 640));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel22.setText("Copyright @TheMob 2023");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 810, -1, -1));

        setSize(new java.awt.Dimension(1523, 828));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

   public void SetTeacherToTable(){
       try{
           Connection con = DriverManager.getConnection(db_url, db_username, db_passwd);
           PreparedStatement pst = con.prepareCall("select * from teachers");
           ResultSet result = pst.executeQuery();
           while(result.next()){
               int teacherId = result.getInt("teacherId");
               String teacherName = result.getString("teacherName");
               String bookName = result.getString("bookName");
               String classes = result.getString("classes");
               int numberOfBooks = result.getInt("numberOfBooks");
               
               
               Object[] obj = {teacherId,teacherName, bookName, classes, numberOfBooks};
               model =(DefaultTableModel ) teacherTable.getModel();
               model.addRow(obj);
               
           }
       }catch(Exception ex){
           ex.printStackTrace();
       }
       
       
   } 
   
   public boolean addTeacher(){
       
       boolean isAdded = false;
       teacherId = Integer.parseInt(teacherIdTxt.getText());
       teacherName = teacherNameTxt.getText();
       bookName = bookCombo.getSelectedItem().toString();
       classes = yearTxt.getText();
       numberOfBooks = Integer.parseInt(numberOfBookTxt.getText());
       try{
           Connection con = DriverManager.getConnection(db_url, db_username, db_passwd);
           String sql = "insert into teachers values(?,?,?,?,?)";
           PreparedStatement pst = con.prepareStatement(sql);
           pst.setInt(1, teacherId);
           pst.setString(2, teacherName);
           pst.setString(3, bookCombo.getSelectedItem().toString());
           pst.setString(4, classes);
           pst.setInt(5, numberOfBooks);
           
           
           
           int rowCount = pst.executeUpdate();
           if(rowCount >0){
               isAdded =true;
               
           }else{
               isAdded =false;
           }
           
       }catch(Exception ex){
           ex.printStackTrace();
       }
    return isAdded;
       
   }
   
   //Clear table
    public void clearTable(){
        DefaultTableModel model = (DefaultTableModel) teacherTable.getModel();
        model.setRowCount(0);
        
    }
    
    public boolean updateTeacher(){
        boolean isUpdated = false;
       teacherId = Integer.parseInt(teacherIdTxt.getText());
       teacherName = teacherNameTxt.getText();
       bookName = bookCombo.getSelectedItem().toString();
       classes = yearTxt.getText();
       numberOfBooks = Integer.parseInt(numberOfBookTxt.getText().toString());
       try{
           Connection con = DriverManager.getConnection(db_url, db_username, db_passwd);
           String sql = "update teachers set teacherName = ?, bookName = ?, classes = ?, numberofbooks = ?  where teacherId = ?";
           PreparedStatement pst = con.prepareStatement(sql);
           pst.setString(1, teacherName);
           pst.setString(2, bookCombo.getSelectedItem().toString());
           pst.setString(3, classes);
           pst.setInt(4, numberOfBooks);
           pst.setInt(5, teacherId);
          
           
           
           int rowCount = pst.executeUpdate();
           if(rowCount > 0){
               isUpdated = true;
           }else{
               isUpdated = false;
           }
       }catch(Exception ex){
           ex.printStackTrace();
       }
       
    return isUpdated;
    }
   
    public boolean deleteTeacher(){
        boolean isDeleted = false;
        teacherId = Integer.parseInt(teacherIdTxt.getText());
       teacherName = teacherNameTxt.getText();
       bookName = bookCombo.getSelectedItem().toString();
       classes = yearTxt.getText();
       numberOfBooks = Integer.parseInt(numberOfBookTxt.getText());
        
        try{
           Connection con = DriverManager.getConnection(db_url, db_username, db_passwd);
           String sql = "delete from teachers where teacherid = ?";
           PreparedStatement pst = con.prepareStatement(sql);
           pst.setInt(1, teacherId);
           
           pst.executeUpdate();
           
           int rowCount = pst.executeUpdate();
           if(rowCount>0){
               isDeleted = true;
           }else{
               isDeleted = false;
           }
        }catch(Exception ex){
            ex.printStackTrace();
        }
        
    return isDeleted;
        
    }
    public void setUpComboBox(){
        
        try{
           bookCombo.removeAllItems();
           Connection con = DriverManager.getConnection(db_url, db_username, db_passwd);
           String sql = "select * from books";
           PreparedStatement pst = con.prepareStatement(sql);
           ResultSet rs = pst.executeQuery();
           while(rs.next()){
               bookCombo.addItem(rs.getString("book_name"));
           }
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }
    
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        HomePage page = new HomePage();
        page.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel23MouseClicked

    private void teacherTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacherTableMouseClicked
        int rowNumber = teacherTable.getSelectedRow();
        TableModel model = teacherTable.getModel();
        
        teacherIdTxt.setText(model.getValueAt(rowNumber, 0).toString());
        teacherNameTxt.setText(model.getValueAt(rowNumber, 1).toString());
        bookCombo.setSelectedItem(model.getValueAt(rowNumber, 2).toString());
        yearTxt.setText(model.getValueAt(rowNumber, 3).toString());
        numberOfBookTxt.setText(model.getValueAt(rowNumber, 4).toString());
        
    }//GEN-LAST:event_teacherTableMouseClicked

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        if(addTeacher() ==true){
            JOptionPane.showMessageDialog(this, "Teacher Added Successfully.");
            clearTable();
            SetTeacherToTable();
        }else{
            JOptionPane.showMessageDialog(this, "Teacher Already Exist!");
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        if(updateTeacher() ==true){
            JOptionPane.showMessageDialog(this, "Teacher Updated Successfully.");
            clearTable();
            SetTeacherToTable();
        }else{
            JOptionPane.showMessageDialog(this, "Teacher Failed To Update!");
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        if(!deleteTeacher()==true){
            JOptionPane.showMessageDialog(this, "Teacher Deleted Successfully.");
            clearTable();
            SetTeacherToTable();
        }else{
            JOptionPane.showMessageDialog(this, "Teacher Failed To Delete!");
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        HomePage page = new HomePage();
        page.setVisible(true);
        dispose();
    }//GEN-LAST:event_jPanel2MouseClicked

    private void bookComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageTeachers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageTeachers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageTeachers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageTeachers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageTeachers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonCircle addBtn;
    private javax.swing.JComboBox<String> bookCombo;
    private rojerusan.RSMaterialButtonCircle deleteBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private app.bolivia.swing.JCTextField numberOfBookTxt;
    private app.bolivia.swing.JCTextField teacherIdTxt;
    private app.bolivia.swing.JCTextField teacherNameTxt;
    private rojeru_san.complementos.RSTableMetro teacherTable;
    private rojerusan.RSMaterialButtonCircle updateBtn;
    private app.bolivia.swing.JCTextField yearTxt;
    // End of variables declaration//GEN-END:variables
}
