/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author nshut
 */
public class ReturnBook extends javax.swing.JFrame {
    private String db_url="jdbc:postgresql://localhost:5432/GS_APACE_LMS";
    private String db_username="postgres";
    private String db_passwd ="2804";
    /**
     * Creates new form IssuedBook
     */
    public ReturnBook() {
        initComponents();
    }
    
    //return the book
    public boolean returnBook(){
        boolean isReturned = false;
        int bookId = Integer.parseInt(bookIdTxt.getText());
        int teacherId = Integer.parseInt(teacherIdTxt.getText());
        
        try{
            Connection con = DriverManager.getConnection(db_url, db_username, db_passwd);
            String sql = ("update issuebooks set status = ? where teacher_id = ? and book_id = ? and status = ?");
            PreparedStatement pst  = con.prepareStatement(sql);
            pst.setString(1, "Returned.");
            pst.setInt(2, teacherId);
            pst.setInt(3, bookId);
            pst.setString(4, "Pending");
            
            int rowCount = pst.executeUpdate();
            if(rowCount>0){
                isReturned = true;
            }else{
                isReturned = false;
            }
            
        }catch(Exception ex){
            ex.printStackTrace();
        }
        
        
        
        
        return isReturned;
        
        
    }
    
    
    
    //To fetch issue book details from DB and display to the panel
    
    public void getIssueBookDetails(){
        
        int bookId = Integer.parseInt(bookIdTxt.getText());
        int teacherId = Integer.parseInt(teacherIdTxt.getText());
        
        try{
            Connection con = DriverManager.getConnection(db_url, db_username, db_passwd);
            String sql = "select * from issuebooks where book_id = ? and teacher_id = ? and status = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1, bookId);
            pst.setInt(2, teacherId);
            pst.setString(3, "Pending");
            
            ResultSet rs = pst.executeQuery();
            
            if(rs.next()){
               
               labelId.setText(rs.getString("id"));
               labelName.setText(rs.getString("book_name"));
               labelTeacher.setText(rs.getString("teacher_id"));
               labelIssue.setText(rs.getString("issue_date"));
               labelRecord.setText(rs.getString("due_date"));
               labelRecord.setText("");
               
            }else{
                labelRecord.setText("No Record Found!");
                
                labelId.setText("");
               labelName.setText("");
               labelTeacher.setText("");
               labelIssue.setText("");
               labelRecord.setText("");
            }
            
        }catch(Exception ex){
            ex.printStackTrace();
        } 
        
    }
    
    
    
    
    //Update book count
    public void updateBookCount(){
        int bookId = Integer.parseInt(bookIdTxt.getText());
        try{
            Connection con = DriverManager.getConnection(db_url, db_username, db_passwd);
            String sql = "update books set quantity = quantity + 1 where book_id= ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1, bookId);
            
            int rowCount = pst.executeUpdate();
            
            if(rowCount>0){
                JOptionPane.showMessageDialog(this, "Book Count Updated.");
            }else{
                
                JOptionPane.showMessageDialog(this, "Can't update Book Count!");
            }
            
        }catch(Exception ex){
            ex.printStackTrace();
                    
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelIssue = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        labelId = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        labelTeacher = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelRecord = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        labelDue1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        bookIdTxt = new app.bolivia.swing.JCTextField();
        teacherIdTxt = new app.bolivia.swing.JCTextField();
        jLabel16 = new javax.swing.JLabel();
        findBtn = new rojerusan.RSMaterialButtonCircle();
        jLabel20 = new javax.swing.JLabel();
        retunBookBtn = new rojerusan.RSMaterialButtonCircle();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 25)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Literature_100px_1.png"))); // NOI18N
        jLabel2.setText("Book Details");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 280, 100));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Issue Date:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, -1, -1));

        labelIssue.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        labelIssue.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(labelIssue, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, 180, 30));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Book Name:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Teacher's Name:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 400, 3));

        jLabel18.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Issue Id:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        labelId.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        labelId.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(labelId, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 180, 30));

        labelName.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        labelName.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(labelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 180, 30));

        labelTeacher.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        labelTeacher.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(labelTeacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 180, 30));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Due Date");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, -1, -1));

        labelRecord.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        labelRecord.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(labelRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 620, 180, 30));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel22.setText("Copyright @TheMob 2023");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 840, -1, -1));

        labelDue1.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        labelDue1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(labelDue1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 520, 180, 30));

        mainPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, -30, 460, 860));

        jPanel6.setBackground(new java.awt.Color(255, 255, 0));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 25)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/stack-of-books.png"))); // NOI18N
        jLabel13.setText("Return Book");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));
        jPanel7.setPreferredSize(new java.awt.Dimension(400, 3));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 400, 3));

        jLabel23.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 0, 0));
        jLabel23.setText("X");
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, -1, -1));

        bookIdTxt.setBackground(new java.awt.Color(255, 255, 0));
        bookIdTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        bookIdTxt.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        bookIdTxt.setPlaceholder("Enter Book Id...");
        bookIdTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                bookIdTxtFocusLost(evt);
            }
        });
        jPanel6.add(bookIdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 300, -1));

        teacherIdTxt.setBackground(new java.awt.Color(255, 255, 0));
        teacherIdTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        teacherIdTxt.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        teacherIdTxt.setPlaceholder("Enter Teacher's ID...");
        teacherIdTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                teacherIdTxtFocusLost(evt);
            }
        });
        jPanel6.add(teacherIdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 300, -1));

        jLabel16.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        jLabel16.setText("Teacher's Id:");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        findBtn.setBackground(new java.awt.Color(102, 102, 255));
        findBtn.setText("FIND");
        findBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findBtnActionPerformed(evt);
            }
        });
        jPanel6.add(findBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 540, 240, 60));

        jLabel20.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        jLabel20.setText("Book Id:");
        jPanel6.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        retunBookBtn.setBackground(new java.awt.Color(0, 0, 0));
        retunBookBtn.setText("RETURN BOOK");
        retunBookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retunBookBtnActionPerformed(evt);
            }
        });
        jPanel6.add(retunBookBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 640, 240, 60));

        mainPanel.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 0, -1, 830));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(102, 102, 255));
        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Rewind_48px.png"))); // NOI18N
        jLabel4.setText("Back");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 40));

        jLabel19.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/library-2.png"))); // NOI18N
        jLabel19.setText("Issue Id:");
        mainPanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 130, 650, -1));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1520, 830));

        setSize(new java.awt.Dimension(1523, 828));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel23MouseClicked

    private void findBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findBtnActionPerformed
        getIssueBookDetails();
    }//GEN-LAST:event_findBtnActionPerformed

    private void bookIdTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bookIdTxtFocusLost
        
    }//GEN-LAST:event_bookIdTxtFocusLost

    private void teacherIdTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_teacherIdTxtFocusLost
       
    }//GEN-LAST:event_teacherIdTxtFocusLost

    private void retunBookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retunBookBtnActionPerformed
       if(returnBook()==true){
           JOptionPane.showMessageDialog(this, "Book Returned Successfully.");
       }else{
           JOptionPane.showMessageDialog(this, "Book Returned Failed!");
       }
    }//GEN-LAST:event_retunBookBtnActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        HomePage page = new HomePage();
        page.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        HomePage page = new HomePage();
        page.setVisible(true);
        dispose();
    }//GEN-LAST:event_jPanel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private app.bolivia.swing.JCTextField bookIdTxt;
    private rojerusan.RSMaterialButtonCircle findBtn;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel labelDue1;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelIssue;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelRecord;
    private javax.swing.JLabel labelTeacher;
    private javax.swing.JPanel mainPanel;
    private rojerusan.RSMaterialButtonCircle retunBookBtn;
    private app.bolivia.swing.JCTextField teacherIdTxt;
    // End of variables declaration//GEN-END:variables
}
